package com.mybatis.demo.rbac.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table file
 */
public class File {
    /**
     */
    private Integer id;

    /**
     */
    private byte[] content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.id
     *
     * @return the value of file.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.id
     *
     * @param id the value for file.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.content
     *
     * @return the value of file.content
     *
     * @mbg.generated
     */
    public byte[] getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.content
     *
     * @param content the value for file.content
     *
     * @mbg.generated
     */
    public void setContent(byte[] content) {
        this.content = content;
    }
}